services:
  # Development service
  app-dev:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    container_name: mynextjs-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    profiles:
      - dev

  # Production service
  app-prod:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    container_name: mynextjs-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    profiles:
      - prod
