---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: mynextjs-app

---
# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: mynextjs-config
  namespace: mynextjs-app
data:
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"
  PORT: "3000"
  HOSTNAME: "0.0.0.0"

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynextjs-app
  namespace: mynextjs-app
  labels:
    app: mynextjs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mynextjs-app
  template:
    metadata:
      labels:
        app: mynextjs-app
    spec:
      containers:
        - name: mynextjs-app
          image: mynextjs-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: mynextjs-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      restartPolicy: Always

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: mynextjs-service
  namespace: mynextjs-app
  labels:
    app: mynextjs-app
spec:
  type: ClusterIP
  selector:
    app: mynextjs-app
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http

---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mynextjs-ingress
  namespace: mynextjs-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
    - host: mynextjs-app.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mynextjs-service
                port:
                  number: 80
  tls:
    - hosts:
        - mynextjs-app.example.com
      secretName: mynextjs-tls

---
# HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: mynextjs-hpa
  namespace: mynextjs-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mynextjs-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
